# Generated by Django 5.2.3 on 2025-06-30 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='egyptian_phone_number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
    ]
