# Generated by Django 5.2.3 on 2025-07-02 00:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_campaign_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
