# Generated by Django 5.2.4 on 2025-07-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_alter_campaign_image_alter_campaign_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='amount_raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
